### ISSUE TITLE
Upgrade to angular4

### ISSUE THREAD

**Issue by psilospore** [psilospore/ng-next-select#3]
We need to make this compatible with angular4.
If you are a collaborator make sure you don't directly commit to development. Create a different branch and bump up the major version number.

**Comment by codinronan** [comment]
@psilospore it is already compatible with angular4, I am importing it into an angular4 project without issue, aside from the install warning about an unmet peer dependency since angular2 is specified.

Is there something that needs to be done aside from just bump up the dependencies, or specify the peer dependencies using an ` || ^4.0.0` ?

**Comment by psilospore** [comment]
@dboss3 is more familiar with this task but yeah it looks like he's mostly just bumped up the dependencies https://github.com/psilospore/ng-next-select/compare/development...psilospore:angular_4_upgrade?expand=1

Also thanks for your interest in our library!

**Comment by codinronan** [comment]
@psilospore oh I didn't even see that branch. Any way you guys can merge that and get it published? I've looked over the changes and aside from the angular version bump the changes are pretty benign.

Love this library. You guys saved me an unimaginable amount of time.

**Comment by psilospore** [comment]
@codinronan thanks! Although we haven't done much additional work on what Valor already built so more credit to them first. We just merged but I'll try to publish by tomorrow.
